-- Fix property-documents storage bucket security exposure
-- Remove overly permissive SELECT policy that allows any authenticated user to read any document
-- Documents should only be accessible via signed URLs generated by the public-doc-url edge function

DROP POLICY IF EXISTS "Users can read property documents" ON storage.objects;

-- No new SELECT policy is needed - all document access should go through:
-- 1. The public-doc-url edge function (validates share token ownership)
-- 2. Direct signed URL generation by the session admin

-- Keep existing INSERT/UPDATE/DELETE policies which properly check ownership